package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
)

const copilotSDKModule = "github.com/github/copilot-sdk/go"

func main() {
	var outputPath string
	flag.StringVar(&outputPath, "output", "", "generated Go output path")
	flag.Parse()

	if err := generate(outputPath); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(outputPath string) error {
	if outputPath == "" {
		return fmt.Errorf("output path is required")
	}

	version, moduleDir, err := copilotSDKModuleInfo()
	if err != nil {
		return err
	}
	sourcePath := filepath.Join(moduleDir, "zsession_events.go")
	source, err := os.ReadFile(sourcePath)
	if err != nil {
		return fmt.Errorf("reading SDK session events from %q: %w", sourcePath, err)
	}
	names, err := parseSessionEventTypeNames(sourcePath, source)
	if err != nil {
		return err
	}
	generated, err := renderSessionEventTypes(version, names)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, generated, 0o644); err != nil {
		return fmt.Errorf("writing generated event types to %q: %w", outputPath, err)
	}
	return nil
}

func copilotSDKModuleInfo() (string, string, error) {
	cmd := exec.Command(
		"go",
		"list",
		"-m",
		"-f",
		"{{.Version}}\t{{.Dir}}",
		copilotSDKModule,
	)
	output, err := cmd.Output()
	if err != nil {
		return "", "", fmt.Errorf("resolving %s from the module graph: %w", copilotSDKModule, err)
	}
	version, moduleDir, ok := strings.Cut(strings.TrimSpace(string(output)), "\t")
	if !ok || version == "" || moduleDir == "" {
		return "", "", fmt.Errorf("unexpected go list output for %s: %q", copilotSDKModule, output)
	}
	return version, moduleDir, nil
}

func parseSessionEventTypeNames(filename string, source []byte) ([]string, error) {
	file, err := parser.ParseFile(token.NewFileSet(), filename, source, 0)
	if err != nil {
		return nil, fmt.Errorf("parsing SDK session events from %q: %w", filename, err)
	}

	names := []string{}
	seen := map[string]struct{}{}
	for _, declaration := range file.Decls {
		constantDeclaration, ok := declaration.(*ast.GenDecl)
		if !ok || constantDeclaration.Tok != token.CONST {
			continue
		}
		for _, specification := range constantDeclaration.Specs {
			valueSpecification, ok := specification.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for _, name := range valueSpecification.Names {
				if !strings.HasPrefix(name.Name, "SessionEventType") {
					continue
				}
				if _, duplicate := seen[name.Name]; duplicate {
					return nil, fmt.Errorf("duplicate SDK session event type constant %q", name.Name)
				}
				seen[name.Name] = struct{}{}
				names = append(names, name.Name)
			}
		}
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("no SDK session event type constants found in %q", filename)
	}
	slices.Sort(names)
	return names, nil
}

func renderSessionEventTypes(version string, names []string) ([]byte, error) {
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintf(&output, "// Source: %s %s.\n\n", copilotSDKModule, version)
	fmt.Fprintln(&output, "package main")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "import copilot %q\n\n", copilotSDKModule)
	fmt.Fprintln(&output, "// knownSDKSessionEventTypes lets validation distinguish event types declared by the pinned SDK.")
	fmt.Fprintln(&output, "var knownSDKSessionEventTypes = map[copilot.SessionEventType]struct{}{")
	for _, name := range names {
		fmt.Fprintf(&output, "\tcopilot.%s: {},\n", name)
	}
	fmt.Fprintln(&output, "}")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated event types: %w", err)
	}
	return formatted, nil
}
